system:
  name: Mango - JCOM

spring:
  profiles:
    active: dev
  thymeleaf:
    mode: HTML5
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss

server:
  port: 8080
  servlet:
    application-display-name: jcom-cms-web
    session:
      timeout: 300D
#    context-path: /jcom

## mybatis
mybatis:
  # 重要配置
  type-aliases-package: com.sw.jcom.domain.model
  mapper-locations: classpath:mapper/*.xml

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#debug: true